services:
  # --- Core Service ---
  ngelmak-core:
    build: .
    container_name: ngelmak-core
    ports:
      - "5742:5742"
    volumes:
      - ./data:/ngelmak/ngelmak-core
    networks:
      - ngelmak-net

networks:
  ngelmak-net:
    external: true