services:
  # --- Core Service ---
  ngelmak-core:
    build: .
    container_name: ngelmak-core
    ports:
      - "5742:5742"
    networks:
      - ngelmak-net

networks:
  ngelmak-net:
    external: true